version: '3'
services:
    site:
        build: .
        container_name: apache
        ports :
        - "3000:80"
        volumes:
        - ./web:/var/www/html/
    database:
        image: mariadb:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Europe/Paris
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
        - database
        ports:
        - 1000:80
        environment:
            MYSQL_ROOT_PASSWORD: password
            PMA_HOST: database